### ISSUE TITLE
Criar DER

### ISSUE THREAD

**Issue by gabrielbaptista** [FabricaAppU9/ChamadaQR#1]

**Comment by gutenbergalmeida** [comment]
![whatsapp image 2017-05-27 at 11 26 27](https://cloud.githubusercontent.com/assets/27260940/26522202/78d7d55a-42d1-11e7-886d-52700967591a.jpeg)

**Comment by eportella** [comment]
Existem algumas observações sobre a modelagem:

- t_perfil que pelo nome se refere a um perfil porem tem fortes traço de ser uma tabela de aluno.

- o usuário carrega um id_presenca, isso demonstra que um usuário só pode ter uma presença.

- as tabelas eventos e t_evento estão competindo na responsabilidade

- a tabela horário evento tem relacionamento implícito com t_evento e explicito com eventos

- todas as tabelas com referência a evento tem data e início e data de finalização do evento.

- algumas redundâncias nos nomes de colunas que torna os scripts mais verboso desnecessariamente. EX: "select e.nome_evento from T_evento as e;" pode ser representado como "select e.nome from evento as e;"

**Comment by eportella** [comment]
Proposta
![image](https://cloud.githubusercontent.com/assets/10750121/26536893/60530ab8-4411-11e7-9112-115b1cffb2c3.png)

**Comment by eportella** [comment]
identificado uma falha na presenca que descreve uma coluna com nome presenca_id na qual deve ser participante_id.
Alterado no Diagrama e tabelas geradas no banco de dados.
