### ISSUE TITLE
Criar diagrama de sequencia

### ISSUE THREAD

**Issue by gabrielbaptista** [FabricaAppU9/ChamadaQR#5]
- Troca de mensagens entre App e Server via QR Code

**Comment by gabrielbaptista** [comment]
Adicionar Thiago

**Comment by eportella** [comment]
@SamTorresmo, obrigado pela contribuição.

**Comment by eportella** [comment]
reaberto, pois não foi identificado o arquivo compartilhado no diretório.

**Comment by SamTorresmo** [comment]
colocado no drive
